### ISSUE TITLE
Driver installtion - check if driver is installed 

### ISSUE THREAD

**Issue by mpalyga** [UsefulScripts01/HPDrivers#1]
Hej. it is wonderful module to PowerShell. however ive looked and see that drivers are installed even if they are already installed in the system. is a chance to add verification and do not install drivers if drivers are in the system and add option -Force to reinstall them if someone needs that ? 

/best regards m.

**Comment by UsefulScripts01** [comment]
Hi mpalyga,
Thanks for your tips! A new version of the HPDrivers module (1.3.2) has been released, which includes the solution you proposed.
