### ISSUE TITLE
Windows version 23H2

### ISSUE THREAD

**Issue by huuub** [UsefulScripts01/HPDrivers#2]
When installing it checks for the current version of windows when you invoke Get-SoftpaqList.
When using this with the new 23H2 it fails because the Get-SoftpaqList does not recognise it.
Maybe you can use a temporary workaround to check it it supports it. If not add OsVer to the command with "22H2"

**Comment by UsefulScripts01** [comment]
Hi Jeroen,
Thank you for your interest and sorry for the late reply. Unfortunately, HP CMSL does not yet officially support 23H2 systems. I updated the module, now all 23H.. systems are treated as 22H2. I will remove this workaround as soon as HP updates HP CMSL.

**Comment by SJBMolSophia** [comment]
Great... thats what I also did. 
I see in the documentation they added it I believe

**Comment by UsefulScripts01** [comment]
I modified the module. Now, each time the module is launched, it will check whether a newer version of HPCMSL is available and install it. The module will also ask you to manually enter the system version if the current HPCMSL does not support it.
I think this completely solves our problem :)
Thanks for the help!

**Comment by huuub** [comment]
I noticed... Well... I use it to completely automate the installation so it was a surprise.

**Comment by UsefulScripts01** [comment]
Guys,
I plan to publish a new version of the HPDrivers module. The new version has been rebuilt and no longer uses HPCMSL. The new module looks promising, is more stable and slightly faster. I tested it on multiple HP machines like ELitebooks G5-G8, ZBook Firefly G7-8 and ZBook Power G5-G10, however, if you want to stay with the current version, please modify your scripts and use the command: Install-Module -Name HPDrivers -RequiredVersion 1.3.8
